In [23]:
import tensorflow as tf
from keras.preprocessing import image
import matplotlib.pyplot as plt
import numpy as np
model = tf.keras.models.load_model('./model/model-test.h5')
# model.summary()

path = './src/images/kaleng.jpg' 
img = image.load_img(path, target_size=(224, 224))
x = image.img_to_array(img)
plt.imshow(x/255.)
x = np.expand_dims(x, axis=0)
images = np.vstack([x])
print(np.array(images[0]))

print("Test DAta:")
# print('{"instances": [\n',np.array3d(images),'\n]}')
# print("Expected Result:",model.predict(x_test[:1]))
# classes = model.predict(images, batch_size=50)
# print(classes[0][0])
# if(classes[0][0] < 0.5):
#     print('Ini sampah organik')
# else:
#     print('Ini sampah anorganik')

[[[165. 151. 138.]
  [167. 153. 140.]
  [169. 155. 142.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[167. 153. 140.]
  [169. 155. 142.]
  [171. 157. 144.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[170. 156. 143.]
  [172. 158. 145.]
  [174. 160. 147.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 ...

 [[181. 177. 174.]
  [182. 178. 175.]
  [180. 176. 173.]
  ...
  [225. 224. 222.]
  [226. 225. 223.]
  [226. 225. 223.]]

 [[181. 177. 174.]
  [182. 178. 175.]
  [180. 176. 173.]
  ...
  [225. 224. 222.]
  [226. 225. 223.]
  [227. 226. 224.]]

 [[181. 177. 174.]
  [183. 179. 176.]
  [182. 178. 175.]
  ...
  [225. 224. 222.]
  [225. 224. 222.]
  [227. 226. 224.]]]
Test DAta:


AttributeError: module 'numpy' has no attribute 'array3d'

In [ ]:
{"instances":[
                [
                    [
                        [165. 151. 138.],
                        [167. 153. 140.],
                        [169. 155. 142.],
                
                        [255. 255. 255.],
                        [255. 255. 255.],
                        [255. 255. 255.],
                    ],

                    [
                        [167. 153. 140.],
                        [169. 155. 142.],
                        [171. 157. 144.],
                
                        [255. 255. 255.],
                        [255. 255. 255.],
                        [255. 255. 255.],
                    ],

                    [
                        [170. 156. 143.],
                        [172. 158. 145.],
                        [174. 160. 147.],
                
                        [255. 255. 255.],
                        [255. 255. 255.],
                        [255. 255. 255.],
                    ],

                

                    [
                        [181. 177. 174.],
                        [182. 178. 175.],
                        [180. 176. 173.],
                        
                        [225. 224. 222.],
                        [226. 225. 223.],
                        [226. 225. 223.],
                    ],

                    [  
                        [181. 177. 174.],
                        [182. 178. 175.],
                        [180. 176. 173.],
                        
                        [225. 224. 222.],
                        [226. 225. 223.],
                        [227. 226. 224.],
                    ],

                    [
                        [181. 177. 174.],
                        [183. 179. 176.],
                        [182. 178. 175.],
                
                        [225. 224. 222.],
                        [225. 224. 222.],
                        [227. 226. 224.],
                    ]
                ]
            ]

}